{{- if and .Values.cni.enabled (eq .Values.cni.type "cilium") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "cni-cilium") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
  overrides: |
    {{- toYaml .Values.cni.cilium.release.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "cni-cilium") | nindent 4 }}
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.cni.cilium.chart | nindent 4 }}
  targetNamespace: {{ .Values.cni.cilium.release.namespace }}
  releaseName: cni-cilium
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "cni-cilium") }}-config
        key: overrides
{{- end }}
